name: 'Setup OpenShift Cluster'
description: 'This action sets up an OpenShift Cluster in your environment'
author: 'Marc Nuri'
branding:
  icon: circle
  color: red
inputs:
  oc version:
    description: 'Version of OpenShift Cluster to deploy'
    required: true
runs:
  using: 'node12'
  main: 'src/index.js'
