name: 'Setup Minishift'
description: 'This actions sets up Minishift in your environment'
author: 'Marc Nuri'
branding:
  icon: circle
  color: red
inputs:
  minishift version:
    description: 'Version of Minishift to deploy'
    required: true
runs:
  using: 'node12'
  main: 'src/index.js'
