name: Main workflow

on: [push]

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@master
      - name: npm install
        run: npm install
      - name: npm test
        run: npm test
