name: Main workflow

on: [push]

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@master
      - name: npm test
        run: npm test
      - name: Run Action
        run: export INPUT_MINISHIFT_VERSION="v1.34.1" && node src/index.js
