name: Main workflow

on: [push]

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Action
        run: export INPUT_VERSION="v1.34.1" && ./entrypoint.sh
